// AUTO-GENERATED FILE
// Generated by: scripts/generate-mfe-manifests.ts
// Do not edit manually!
// Regenerate: npm run generate:mfe-manifests

import type { Extension, JSONSchema, MfeEntry } from '@hai3/react';

export interface MfeManifestConfig {
  manifest: JSONSchema;
  entries: MfeEntry[];
  extensions: Extension[];
}

export const MFE_MANIFESTS: MfeManifestConfig[] = [];
